version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env


  web:
    build: .
    restart: always
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .src:/app
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
