# Generated by Django 5.0.1 on 2025-03-31 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version_number", models.IntegerField()),
                ("file", models.FileField(blank=True, null=True, upload_to="files/")),
                ("url", models.CharField(db_index=True, max_length=512)),
                ("file_name", models.CharField(max_length=512)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("url", "version_number")},
            },
        ),
    ]
