# Generated by Django 5.0.1 on 2025-03-31 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileversion",
            name="file_name",
        ),
    ]
