# Generated by Django 5.0.1 on 2025-03-31 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_remove_fileversion_file_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fileversion",
            unique_together={("url", "version_number")},
        ),
    ]
