# Generated by Django 5.0.1 on 2025-03-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_alter_fileversion_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="file_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
