# Generated by Django 5.0.1 on 2025-03-31 17:33

import propylon_document_manager.accounts.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", propylon_document_manager.accounts.models.UserManager()),
            ],
        ),
    ]
